#!/bin/sh
# .dira/hook.sh — portable dira hook forwarder, generated by `dira cloud init`.
# Invoked by committed harness hook configs as: sh .dira/hook.sh <harness>
#
# Contract (mirrors `dira hook <harness>` exactly): ALWAYS exit 0, write
# nothing to stdout, never block the agent loop. A machine without a dira
# binary is simply not instrumented — the event is dropped silently, the same
# way a stopped daemon drops it.
#
# Do not hand-edit; re-run `dira cloud init` to regenerate.

harness="${1:-claude}"

find_dira() {
  if command -v dira >/dev/null 2>&1; then
    command -v dira
    return 0
  fi
  for candidate in "$HOME/.local/bin/dira" /usr/local/bin/dira; do
    if [ -x "$candidate" ]; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done
  return 1
}

if bin="$(find_dira)"; then
  # `dira hook` reads the event JSON from our inherited stdin and always
  # exits 0 within its own 2s budget.
  #
  # DIRA_HOOK_VIA=portable marks this invocation as having come through the
  # repo-committed wrapper, so `dira hook` can yield to live user-scope
  # wiring for the same event instead of forwarding it twice.
  DIRA_HOOK_VIA=portable
  export DIRA_HOOK_VIA
  exec "$bin" hook "$harness"
fi
exit 0
