//! OpenCode hook normalization.
//!
//! OpenCode has no command-hook system; instead it loads JS/TS plugins. We ship a
//! tiny forwarder plugin (`dira init opencode` writes it) that HTTP-POSTs a small
//! JSON object to the daemon's `/hooks/opencode` route on the lifecycle and tool
//! events that matter. Crucially, `tool.execute.before/after` and `permission.ask`
//! are plugin-only hooks (they are NOT exposed on OpenCode's SSE event stream), so
//! the plugin is the only way to observe tool activity.
//!
//! The plugin already speaks Dira's vocabulary, so the wire shape is just:
//! `{ kind, session_id, cwd?, tool_name?, transcript_path? }` where `kind` is one
//! of the [`EventKind`]-aligned strings below. `normalize()` maps `kind` directly.
//!
//! TODO(version-verify): the plugin hook names (`event` with
//! `session.idle`/`session.start`, `tool.execute.before/after`, `permission.ask`,
//! `chat.message`) are mapped in the bundled plugin, not here. Re-verify those
//! against the shipping OpenCode plugin API before GA.

use crate::{HarnessSource, Normalized};
use dira_contract::Harness;
use dira_core::model::EventKind;
use serde::Deserialize;

/// The JSON shape the bundled OpenCode plugin POSTs to `/hooks/opencode`. The
/// plugin pre-translates OpenCode's hook names into our `kind` vocabulary, so all
/// we do is parse + map. Unknown fields are ignored.
#[derive(Debug, Clone, Deserialize)]
pub struct OpenCodeHook {
    /// One of: `SessionStart`, `SessionEnd`, `UserPrompt`, `PreTool`, `PostTool`,
    /// `PermissionDecision`, `Stop`.
    #[serde(default)]
    pub kind: Option<String>,
    #[serde(default)]
    pub session_id: Option<String>,
    #[serde(default)]
    pub cwd: Option<String>,
    #[serde(default)]
    pub tool_name: Option<String>,
    #[serde(default)]
    pub transcript_path: Option<String>,
}

/// Map an OpenCode plugin hook to a normalized event. `kind` is our own
/// vocabulary, so the mapping is direct; unknown kinds are ignored.
pub fn normalize(hook: &OpenCodeHook) -> Option<Normalized> {
    let kind = map_kind(hook.kind.as_deref()?)?;
    Some(Normalized {
        session_id: hook
            .session_id
            .clone()
            .unwrap_or_else(|| "unknown".to_string()),
        kind,
        cwd: hook.cwd.clone(),
        tool: hook.tool_name.clone(),
        transcript_path: hook.transcript_path.clone(),
    })
}

/// Map a Dira-vocabulary `kind` string to its [`EventKind`].
pub(crate) fn map_kind(kind: &str) -> Option<EventKind> {
    Some(match kind {
        "SessionStart" => EventKind::SessionStart,
        "SessionEnd" => EventKind::SessionEnd,
        "UserPrompt" => EventKind::UserPrompt,
        "PreTool" => EventKind::PreTool,
        "PostTool" => EventKind::PostTool,
        "PermissionDecision" => EventKind::PermissionDecision,
        "Stop" => EventKind::Stop,
        _ => return None,
    })
}

/// The OpenCode source.
pub struct OpenCodeSource;

impl HarnessSource for OpenCodeSource {
    fn harness(&self) -> Harness {
        Harness::OpenCode
    }
    fn id(&self) -> &'static str {
        "opencode"
    }
    fn normalize(&self, payload: serde_json::Value) -> Option<Normalized> {
        let hook: OpenCodeHook = serde_json::from_value(payload).ok()?;
        normalize(&hook)
    }
}

/// The forwarder plugin `dira init opencode` writes to
/// `~/.config/opencode/plugin/dira.js`. It POSTs the Dira-vocabulary JSON above
/// to the daemon on the relevant OpenCode plugin hooks. `{BEARER}` and `{URL}` are
/// substituted by the writer.
pub fn plugin_js(daemon_url: &str, bearer: &str) -> String {
    PLUGIN_TEMPLATE
        .replace("{URL}", daemon_url)
        .replace("{BEARER}", bearer)
}

/// The plugin body, with `{URL}`/`{BEARER}` placeholders. Kept as a template so the
/// daemon endpoint + token are stamped at `dira init` time.
const PLUGIN_TEMPLATE: &str = r#"// dira OpenCode forwarder — auto-generated by `dira init opencode`.
// Forwards lifecycle + tool + permission events to the local dira daemon.
// Metadata only: session id, cwd, tool name. Never prompt text or tool output.
const DIRA_URL = "{URL}/hooks/opencode";
const DIRA_BEARER = "{BEARER}";

async function send(kind, data) {
  try {
    await fetch(DIRA_URL, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: "Bearer " + DIRA_BEARER,
      },
      body: JSON.stringify({ kind, ...data }),
    });
  } catch (_) {
    // Never break the agent loop on a transport error.
  }
}

export const DiraPlugin = async ({ directory }) => {
  const cwd = directory;
  return {
    event: async ({ event }) => {
      if (event.type === "session.start") {
        await send("SessionStart", { session_id: event.properties?.sessionID, cwd });
      } else if (event.type === "session.idle") {
        await send("Stop", { session_id: event.properties?.sessionID, cwd });
      } else if (event.type === "session.deleted" || event.type === "session.end") {
        await send("SessionEnd", { session_id: event.properties?.sessionID, cwd });
      } else if (event.type === "chat.message") {
        await send("UserPrompt", { session_id: event.properties?.sessionID, cwd });
      }
    },
    "tool.execute.before": async (input) => {
      await send("PreTool", { session_id: input?.sessionID, cwd, tool_name: input?.tool });
    },
    "tool.execute.after": async (input) => {
      await send("PostTool", { session_id: input?.sessionID, cwd, tool_name: input?.tool });
    },
    "permission.ask": async (input) => {
      await send("PermissionDecision", { session_id: input?.sessionID, cwd });
    },
  };
};
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn maps_each_kind() {
        let cases = [
            ("SessionStart", EventKind::SessionStart),
            ("SessionEnd", EventKind::SessionEnd),
            ("UserPrompt", EventKind::UserPrompt),
            ("PreTool", EventKind::PreTool),
            ("PostTool", EventKind::PostTool),
            ("PermissionDecision", EventKind::PermissionDecision),
            ("Stop", EventKind::Stop),
        ];
        for (kind, expect) in cases {
            let hook: OpenCodeHook = serde_json::from_value(
                serde_json::json!({"kind": kind, "session_id": "s", "cwd": "/r"}),
            )
            .unwrap();
            let n = normalize(&hook).unwrap();
            assert_eq!(n.kind, expect, "kind {kind}");
            assert_eq!(n.session_id, "s");
        }
    }

    #[test]
    fn pretool_carries_tool_name() {
        let hook: OpenCodeHook =
            serde_json::from_str(r#"{"kind":"PreTool","session_id":"s","tool_name":"bash"}"#)
                .unwrap();
        let n = normalize(&hook).unwrap();
        assert_eq!(n.kind, EventKind::PreTool);
        assert_eq!(n.tool.as_deref(), Some("bash"));
    }

    #[test]
    fn unknown_kind_is_ignored() {
        let hook: OpenCodeHook =
            serde_json::from_str(r#"{"kind":"Whatever","session_id":"s"}"#).unwrap();
        assert!(normalize(&hook).is_none());
    }

    #[test]
    fn plugin_substitutes_url_and_bearer() {
        let js = plugin_js("http://127.0.0.1:9999", "tok-123");
        assert!(js.contains("http://127.0.0.1:9999/hooks/opencode"));
        assert!(js.contains("tok-123"));
        assert!(!js.contains("{URL}"));
        assert!(!js.contains("{BEARER}"));
    }
}
