//! Model-price resolution against a bundled table.
//!
//! The table (`cli/core/pricing/models.json`) is generated from
//! <https://models.dev/api.json> by `just pricing-sync` and refreshed monthly by
//! `.github/workflows/pricing-sync.yml` — never hand-edited. It is compiled into
//! the binary, so a fresh install prices offline and an old binary keeps
//! whatever table it shipped with.
//!
//! **The cloud is authoritative and this table is allowed to drift.** The cloud
//! keeps its own copy on the same monthly cadence and re-prices historical rows;
//! `est_cost_usd` on the wire is contract-documented as a label, never a billing
//! base. This copy exists so the LOCAL views (`dira status`, `dira report`) have
//! a number to show without a round trip.
//!
//! The matching cascade is a port of the cloud's `resolve.ts`, deliberately
//! kept step-for-step identical so the two agree on any id either can see.
//! Matching on family substrings — what this replaced — is not an option: a
//! rule like "contains opus" cannot express that `claude-opus-4-1` is $15/$75
//! while every opus from 4-5 on is $5/$25, so it silently encodes whichever
//! generation it was written against and priced the current models at 3x.

use std::collections::BTreeMap;
use std::sync::OnceLock;

/// USD per 1M tokens. Cache rates are 0.0 when the provider publishes none —
/// treated as free rather than guessed, matching the cloud.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PriceEntry {
    pub input: f64,
    pub output: f64,
    pub cache_read: f64,
    pub cache_write: f64,
}

#[derive(serde::Deserialize)]
struct RawEntry {
    input: f64,
    output: f64,
    #[serde(default, rename = "cacheRead")]
    cache_read: Option<f64>,
    #[serde(default, rename = "cacheWrite")]
    cache_write: Option<f64>,
}

#[derive(serde::Deserialize)]
struct Artifact {
    models: BTreeMap<String, Option<RawEntry>>,
}

/// The generated table, compiled in. Regenerated by `just pricing-sync`.
const TABLE_JSON: &str = include_str!("../pricing/models.json");
/// Hand corrections merged over it — overrides win, and a `null` suppresses a
/// bad upstream entry. Never touched by the sync.
///
/// This is where ids the generated catalog cannot carry belong: notably the
/// bare `grok` label dira itself synthesizes when a grok turn reports no
/// per-model breakdown, which is a dira-internal string models.dev has never
/// heard of.
const OVERRIDES_JSON: &str = include_str!("../pricing/overrides.json");

fn parse(json: &str, what: &str) -> BTreeMap<String, Option<PriceEntry>> {
    // A malformed bundled table is a build-time mistake, not a runtime
    // condition — but a panic here would take down the daemon over a cost
    // *label*, so it degrades to empty and every model falls back (and is
    // reported by `tokens::warn_if_unpriced`).
    match serde_json::from_str::<Artifact>(json) {
        Ok(a) => a
            .models
            .into_iter()
            .map(|(k, v)| {
                let e = v.map(|v| PriceEntry {
                    input: v.input,
                    output: v.output,
                    cache_read: v.cache_read.unwrap_or(0.0),
                    cache_write: v.cache_write.unwrap_or(0.0),
                });
                (k, e)
            })
            .collect(),
        Err(e) => {
            tracing::error!("bundled {what} table is unparseable: {e}");
            BTreeMap::new()
        }
    }
}

fn table() -> &'static BTreeMap<String, PriceEntry> {
    static TABLE: OnceLock<BTreeMap<String, PriceEntry>> = OnceLock::new();
    TABLE.get_or_init(|| {
        let mut merged = parse(TABLE_JSON, "pricing");
        merged.extend(parse(OVERRIDES_JSON, "pricing overrides"));
        merged
            .into_iter()
            .filter_map(|(k, v)| Some((k, v?)))
            .collect()
    })
}

/// Canonicalize an observed model string toward the table's bare-id keys.
///
/// Harnesses report models in whatever shape their provider uses: bare ids,
/// provider-prefixed, Bedrock regional ARNs, Vertex `@version` pins. Each step
/// peels one wrapper layer, in order. Shared with the sync bin so the table is
/// keyed exactly the way lookups spell it.
pub fn normalize_model(raw: &str) -> String {
    let mut m = raw.trim().to_ascii_lowercase();

    // Provider/reseller path prefixes: "openrouter/anthropic/claude-…".
    if let Some(i) = m.rfind('/') {
        m = m[i + 1..].to_string();
    }
    // Bedrock regional prefixes ("us.anthropic.claude…").
    for p in ["us.", "eu.", "apac.", "jp.", "au.", "ca.", "global."] {
        if let Some(rest) = m.strip_prefix(p) {
            m = rest.to_string();
            break;
        }
    }
    // Vendor dot-prefixes.
    for p in [
        "anthropic.",
        "amazon.",
        "meta.",
        "mistral.",
        "ai21.",
        "cohere.",
        "deepseek.",
    ] {
        if let Some(rest) = m.strip_prefix(p) {
            m = rest.to_string();
            break;
        }
    }
    m = strip_bedrock_version(&m);
    m = strip_vertex_version(&m);
    m
}

/// Trailing `-v1` / `-v1:0` (Bedrock).
fn strip_bedrock_version(m: &str) -> String {
    let Some(i) = m.rfind("-v") else {
        return m.to_string();
    };
    let tail = &m[i + 2..];
    let ok = !tail.is_empty()
        && tail
            .split_once(':')
            .map_or(tail.chars().all(|c| c.is_ascii_digit()), |(a, b)| {
                !a.is_empty()
                    && !b.is_empty()
                    && a.chars().all(|c| c.is_ascii_digit())
                    && b.chars().all(|c| c.is_ascii_digit())
            });
    if ok {
        m[..i].to_string()
    } else {
        m.to_string()
    }
}

/// Trailing `@version` (Vertex).
fn strip_vertex_version(m: &str) -> String {
    match m.rfind('@') {
        Some(i)
            if m[i + 1..]
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '.' || c == '-')
                && i + 1 < m.len() =>
        {
            m[..i].to_string()
        }
        _ => m.to_string(),
    }
}

/// Strip release pins that point at a family key: `-20251001`, `-latest`.
///
/// Public so the sync bin can drop dated aliases the cascade would never reach.
/// It must be this exact function: a second copy could disagree and prune an
/// entry that lookups still need.
pub fn strip_release(id: &str) -> String {
    let s = id.strip_suffix("-latest").unwrap_or(id);
    // `-20\d{6}`
    if s.len() > 9 {
        let (head, tail) = s.split_at(s.len() - 9);
        if let Some(digits) = tail.strip_prefix('-') {
            if digits.starts_with("20") && digits.chars().all(|c| c.is_ascii_digit()) {
                return head.to_string();
            }
        }
    }
    s.to_string()
}

/// Resolve an observed model string to a bundled price.
///
/// Cascade, first hit wins:
///   1. exact (lowercased) key
///   2. normalized key (prefixes/version wrappers stripped)
///   3. normalized key with date/`-latest` pins stripped
///   4. longest table key that is a `-`-boundary prefix of (3)
///
/// Step 4's boundary check is what stops an unknown point release from
/// matching mid-token: `claude-sonnet-x` must NOT resolve to `claude-sonnet-5`.
///
/// `None` means nothing matched; the caller supplies its own fallback.
pub fn resolve(raw: &str) -> Option<(&'static str, PriceEntry)> {
    let t = table();
    let exact = raw.trim().to_ascii_lowercase();
    if let Some((k, v)) = t.get_key_value(&exact) {
        return Some((k.as_str(), *v));
    }
    let normalized = normalize_model(raw);
    if let Some((k, v)) = t.get_key_value(&normalized) {
        return Some((k.as_str(), *v));
    }
    let bare = strip_release(&normalized);
    if let Some((k, v)) = t.get_key_value(&bare) {
        return Some((k.as_str(), *v));
    }

    let mut best: Option<(&'static str, PriceEntry)> = None;
    for (key, v) in t.iter() {
        let Some(rest) = bare.strip_prefix(key.as_str()) else {
            continue;
        };
        if !(rest.is_empty() || rest.starts_with('-')) {
            continue;
        }
        if best.is_none_or(|(b, _)| key.len() > b.len()) {
            best = Some((key.as_str(), *v));
        }
    }
    best
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The sync drops a dated alias whose undated form carries the same price,
    /// because the cascade strips the pin before looking up. This pins BOTH
    /// halves: the table really is free of them, and every one still resolves —
    /// so a future regeneration that stopped pruning (bloat) or pruned a
    /// price-bearing pin (silently wrong) is caught here.
    #[test]
    fn dated_aliases_are_pruned_but_still_resolve() {
        let t = table();
        for key in t.keys() {
            let base = strip_release(key);
            if base == *key {
                continue;
            }
            assert!(
                t.get(&base).is_none_or(|b| b != &t[key]),
                "{key} duplicates {base} at the same price and should have been pruned"
            );
        }
        // The four Anthropic aliases the sync actually drops today.
        for (dated, undated) in [
            ("claude-opus-4-1-20250805", "claude-opus-4-1"),
            ("claude-opus-4-5-20251101", "claude-opus-4-5"),
            ("claude-sonnet-4-5-20250929", "claude-sonnet-4-5"),
            ("claude-haiku-4-5-20251001", "claude-haiku-4-5"),
        ] {
            assert!(!t.contains_key(dated), "{dated} should be pruned");
            assert_eq!(
                resolve(dated).unwrap().1,
                resolve(undated).unwrap().1,
                "{dated} must still price as {undated}"
            );
        }
    }

    /// Only models a coding harness can drive are vendored — tool calling is the
    /// interaction model for every supported harness, so embeddings, image/TTS
    /// models and pre-tool chat models can never produce a captured turn.
    #[test]
    fn non_tool_calling_models_are_not_vendored() {
        let t = table();
        for id in [
            "text-embedding-3-large",
            "text-embedding-ada-002",
            "gpt-3.5-turbo",
            "gemini-embedding-001",
        ] {
            assert!(!t.contains_key(id), "{id} should not be in the table");
        }
    }

    /// Pinning literal ids here used to be brittle — a monthly re-sync could drop
    /// one and the test would rot silently until something noticed prices were
    /// missing. The sync is now append-only (it never drops a vendored id), so
    /// pinning is safe, and doing so buys something a looser family/substring
    /// check does not: a whole provider vanishing from the catalog fails here,
    /// not just a stale id. One id per supported harness family, plus the full
    /// Anthropic generation lineup dira actually observes today.
    #[test]
    fn the_bundled_table_parses_and_covers_every_harness_family() {
        let t = table();
        assert!(t.len() > 50, "table looks truncated: {} entries", t.len());
        for id in [
            // Anthropic (Claude Code): every generation in active use.
            "claude-opus-5",
            "claude-opus-4-8",
            "claude-sonnet-5",
            "claude-haiku-4-5",
            "claude-fable-5",
            "claude-fable-5-1",
            // One id per remaining supported harness family.
            "gpt-5.3-codex",          // openai/Codex
            "gemini-3.1-pro-preview", // google/Gemini CLI
            "grok-4.5",               // xai
        ] {
            // Presence in the table, not `resolve().is_some()`: the cascade's
            // prefix step would answer for a missing id out of a shorter
            // sibling and hide the gap. That is exactly how `claude-fable-5-1`
            // read as priced while it was absent — it matched `claude-fable-5`
            // and inherited a cache-read rate four times its own.
            assert!(t.contains_key(id), "{id} must be a table entry");
        }
    }

    /// The defect this module replaced: family substrings cannot express a
    /// mid-family re-price, and opus was re-priced at 4-5.
    #[test]
    fn generations_resolve_to_their_own_price() {
        let (_, old) = resolve("claude-opus-4-1").unwrap();
        let (_, new) = resolve("claude-opus-4-8").unwrap();
        assert_eq!((old.input, old.output), (15.0, 75.0));
        assert_eq!((new.input, new.output), (5.0, 25.0));
        assert_eq!(new.cache_read, 0.5);

        let (_, s5) = resolve("claude-sonnet-5").unwrap();
        let (_, s46) = resolve("claude-sonnet-4-6").unwrap();
        assert_eq!(s5.input, 2.0);
        assert_eq!(s46.input, 3.0);
    }

    #[test]
    fn wrapper_forms_collapse_onto_the_bare_id() {
        let bare = resolve("claude-opus-4-8").unwrap().1;
        for wrapped in [
            "anthropic/claude-opus-4-8",
            "openrouter/anthropic/claude-opus-4-8",
            "us.anthropic.claude-opus-4-8-v1:0",
            "claude-opus-4-8@20260101",
            "  CLAUDE-OPUS-4-8  ",
        ] {
            assert_eq!(resolve(wrapped).unwrap().1, bare, "{wrapped}");
        }
    }

    #[test]
    fn a_dated_point_release_falls_back_to_its_family_key() {
        // Not in the table verbatim, but the date pin strips to one that is.
        let dated = resolve("claude-opus-4-8-20260101").unwrap().1;
        assert_eq!(dated, resolve("claude-opus-4-8").unwrap().1);
    }

    /// Step 4 must match on `-` boundaries only, or an unknown model silently
    /// inherits a neighbour's price.
    #[test]
    fn prefix_matching_respects_token_boundaries() {
        // "claude-sonnet-5" is a table key; "claude-sonnet-55" must not hit it.
        assert!(resolve("claude-sonnet-55").is_none_or(|(k, _)| k != "claude-sonnet-5"));
        // A genuinely unknown model resolves to nothing at all.
        assert!(resolve("totally-made-up-model-9").is_none());
    }
}
